// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMQ_8I1fabM0u956MnInJ9z8YGh6o1P_0',
    appId: '1:870497548445:web:439cfe132433a5e8107c74',
    messagingSenderId: '870497548445',
    projectId: 'imedcom-patient-app',
    authDomain: 'imedcom-patient-app.firebaseapp.com',
    storageBucket: 'imedcom-patient-app.appspot.com',
    measurementId: 'G-EVG57L12C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH8Tq4NrYFLvfENQAlDElkeNwju7IWFWM',
    appId: '1:870497548445:android:95e9cd4109504c71107c74',
    messagingSenderId: '870497548445',
    projectId: 'imedcom-patient-app',
    storageBucket: 'imedcom-patient-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzEihoUy92NbU9qNf8lcPfpSf4dAA7WM0',
    appId: '1:870497548445:ios:e91195b0cc30d5ff107c74',
    messagingSenderId: '870497548445',
    projectId: 'imedcom-patient-app',
    storageBucket: 'imedcom-patient-app.appspot.com',
    iosClientId:
        '870497548445-vbnph7hjabh3ek1su1srl0q49qj8gcea.apps.googleusercontent.com',
    iosBundleId: 'com.imedcom.iMedCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzEihoUy92NbU9qNf8lcPfpSf4dAA7WM0',
    appId: '1:870497548445:ios:513fa33e3bef7ff4107c74',
    messagingSenderId: '870497548445',
    projectId: 'imedcom-patient-app',
    storageBucket: 'imedcom-patient-app.appspot.com',
    iosClientId:
        '870497548445-79vanc1ru1343v8efh06nmc7qkdrutqa.apps.googleusercontent.com',
    iosBundleId: 'com.imedcom.patientApp',
  );
}
